Debug test 3.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -134,105 +134,105 @@ jobs:
         run: cmake --build build-wasm
       - name: Unit testing
         run: cmake --build build-wasm --target jest_test
-  code_formatting:
-    name: Code formatting
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-    steps:
-      - name: Check out libCellML
-        uses: actions/checkout@v4
-      - name: Install ClangFormat
-        run: |
-          sudo apt update
-          sudo apt install clang-format
-      - name: Install CMake and Ninja
-        uses: lukka/get-cmake@latest
-      - name: Configure libCellML
-        run: |
-          mkdir build
-          cd build
-          cmake -G Ninja ..
-      - name: Code formatting
-        run: |
-          cd build
-          ninja test_clang_format
-  coverage:
-    name: Code coverage
-    runs-on: macos-latest
-    strategy:
-      fail-fast: false
-    steps:
-      - name: Check out libCellML
-        uses: actions/checkout@v4
-      - name: Install CMake and Ninja
-        uses: lukka/get-cmake@latest
-      - name: Install buildcache
-        uses: cscouto/buildcache-action@v1
-      - name: Install LLVM
-        run: |
-          brew install --overwrite llvm
-          echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.bash_profile
-      - name: Configure libCellML
-        run: |
-          mkdir build
-          cd build
-          cmake -G Ninja -DBINDINGS_PYTHON=OFF ..
-      - name: Code coverage
-        run: |
-          cd build
-          ninja llvm_coverage
-          if [ `ninja llvm_coverage | grep TOTAL | sed 's/ /\n/g' | grep "100.00%" | wc -l | sed 's/ //g'` -eq 4 ]; then exit 0; else exit 1; fi
-  memory_leaks:
-    name: Memory leaks
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-    steps:
-      - name: Check out libCellML
-        uses: actions/checkout@v4
-      - name: Install CMake and Ninja
-        uses: lukka/get-cmake@latest
-      - name: Install buildcache
-        uses: cscouto/buildcache-action@v1
-      - name: Install Valgrind
-        run: |
-          sudo apt update
-          sudo apt install valgrind
-      - name: Configure libCellML
-        run: |
-          mkdir build
-          cd build
-          cmake -G Ninja -DBINDINGS_PYTHON=OFF ..
-      - name: Memory leaks
-        run: |
-          cd build
-          ninja memcheck
-  documentation:
-    name: Documentation
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-    steps:
-      - name: Check out libCellML
-        uses: actions/checkout@v4
-      - name: Install CMake and Ninja
-        uses: lukka/get-cmake@latest
-      - name: Install buildcache
-        uses: cscouto/buildcache-action@v1
-      - name: Install Doxygen
-        run: |
-          sudo apt update
-          sudo apt install doxygen
-      - name: Install Sphinx
-        run: |
-          pip3 install sphinx
-      - name: Configure libCellML
-        run: |
-          mkdir build
-          cd build
-          cmake -G Ninja -DBINDINGS_PYTHON=OFF ..
-      - name: Documentation
-        run: |
-          cd build
-          ninja docs
+  # code_formatting:
+  #   name: Code formatting
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #   steps:
+  #     - name: Check out libCellML
+  #       uses: actions/checkout@v4
+  #     - name: Install ClangFormat
+  #       run: |
+  #         sudo apt update
+  #         sudo apt install clang-format
+  #     - name: Install CMake and Ninja
+  #       uses: lukka/get-cmake@latest
+  #     - name: Configure libCellML
+  #       run: |
+  #         mkdir build
+  #         cd build
+  #         cmake -G Ninja ..
+  #     - name: Code formatting
+  #       run: |
+  #         cd build
+  #         ninja test_clang_format
+  # coverage:
+  #   name: Code coverage
+  #   runs-on: macos-latest
+  #   strategy:
+  #     fail-fast: false
+  #   steps:
+  #     - name: Check out libCellML
+  #       uses: actions/checkout@v4
+  #     - name: Install CMake and Ninja
+  #       uses: lukka/get-cmake@latest
+  #     - name: Install buildcache
+  #       uses: cscouto/buildcache-action@v1
+  #     - name: Install LLVM
+  #       run: |
+  #         brew install --overwrite llvm
+  #         echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.bash_profile
+  #     - name: Configure libCellML
+  #       run: |
+  #         mkdir build
+  #         cd build
+  #         cmake -G Ninja -DBINDINGS_PYTHON=OFF ..
+  #     - name: Code coverage
+  #       run: |
+  #         cd build
+  #         ninja llvm_coverage
+  #         if [ `ninja llvm_coverage | grep TOTAL | sed 's/ /\n/g' | grep "100.00%" | wc -l | sed 's/ //g'` -eq 4 ]; then exit 0; else exit 1; fi
+  # memory_leaks:
+  #   name: Memory leaks
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #   steps:
+  #     - name: Check out libCellML
+  #       uses: actions/checkout@v4
+  #     - name: Install CMake and Ninja
+  #       uses: lukka/get-cmake@latest
+  #     - name: Install buildcache
+  #       uses: cscouto/buildcache-action@v1
+  #     - name: Install Valgrind
+  #       run: |
+  #         sudo apt update
+  #         sudo apt install valgrind
+  #     - name: Configure libCellML
+  #       run: |
+  #         mkdir build
+  #         cd build
+  #         cmake -G Ninja -DBINDINGS_PYTHON=OFF ..
+  #     - name: Memory leaks
+  #       run: |
+  #         cd build
+  #         ninja memcheck
+  # documentation:
+  #   name: Documentation
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #   steps:
+  #     - name: Check out libCellML
+  #       uses: actions/checkout@v4
+  #     - name: Install CMake and Ninja
+  #       uses: lukka/get-cmake@latest
+  #     - name: Install buildcache
+  #       uses: cscouto/buildcache-action@v1
+  #     - name: Install Doxygen
+  #       run: |
+  #         sudo apt update
+  #         sudo apt install doxygen
+  #     - name: Install Sphinx
+  #       run: |
+  #         pip3 install sphinx
+  #     - name: Configure libCellML
+  #       run: |
+  #         mkdir build
+  #         cd build
+  #         cmake -G Ninja -DBINDINGS_PYTHON=OFF ..
+  #     - name: Documentation
+  #       run: |
+  #         cd build
+  #         ninja docs
